config/routes.rb
Doxnews::Application.routes.draw do
  root "welcome#index"

  resources :posts do
    member do
      post :up_vote
      post :down_vote
    end
  end
  resources :users
  resources :sessions

  get  'my_posts' => 'posts#my_posts'
  get  'log_in'   => 'users#log_in'
  post 'log_out'  => 'sessions#log_out'
end

app/models/down_vote.rb
class DownVote < Vote

  after_create :increase_counter

  def increase_counter
    post.increment!(:down_votes_count) if post
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  title      :string(255)      not null
#  url        :text
#  body       :text
#  state      :string(255)      default("published")
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base

  belongs_to :user

  has_many :up_votes
  has_many :down_votes

  validates :title, presence: true
  validates :url, presence: true

  attr_accessible :title, :url, :body

  # scopes
  def self.state(state = 'published'); where(:state => state).order(:created_at) end
end

app/models/up_vote.rb
class UpVote < Vote

  belongs_to :post, counter_cache: true

  after_create :increase_counter

  def increase_counter
    post.increment!(:up_votes_count) if post
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :posts
  has_many :up_votes
  has_many :down_votes

  validates_presence_of :password, :on => :create
  validates_presence_of :email, :name

  attr_accessible :name, :email, :password, :password_confirmation
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :user_id, :scope => :post_id
  validates_presence_of :user, :post

  attr_accessible :post_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def logout_required
    redirect_to posts_path if logged_in?
  end

  def login_required
    redirect_to new_user_path, :notice => 'You must sign in first' unless logged_in?
  end

  def admin_required
    redirect_to posts_path, :notice => 'Only admins can do that' unless logged_in? && current_user.admin?
  end

  def logged_in?
    current_user
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :login_required
  before_filter :admin_required, :only => [ :destroy, :down_vote ]

  def index
    @posts = Post.state('published').paginate(:page => params[:page])
  end

  def my_posts
    params[:state] ||= "published"
    @posts = current_user.posts.state(params[:state]).paginate(:page => params[:page])
    render :index
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.create(params[:post])
    if @post.save
      redirect_to posts_path, :notice => t("controllers.posts.create.success")
    else
      flash[:notice] = t("controllers.posts.create.failure")
      render :new
    end
  end

  def up_vote
    up_vote = current_user.up_votes.new(:post_id => params[:id])

    if up_vote.save
      redirect_to posts_path(:page => params[:page]), :notice => 'Up Voted sucessfully'
    else
      redirect_to posts_path(:page => params[:page]), :notice =>  "#{up_vote.errors.full_messages.first}"
    end
  end

  def down_vote
    down_vote = current_user.down_votes.new(:post_id => params[:id])

    if down_vote.save
      redirect_to posts_path(:page => params[:page]), :notice => 'Down Voted sucessfully'
    else
      redirect_to posts_path(:page => params[:page]), :notice =>  "#{down_vote.errors.full_messages.first}"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    if @post.errors.any?
      redirect_to posts_path(:page => params[:page]), :notice =>  "#{@post.errors.full_messages.first}"
    else
      redirect_to posts_path(:page => params[:page]), :notice => 'Post deleted sucessfully'
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def create
  user = User.find_by_email(params[:email])
  if user && user.authenticate(params[:password])
    session[:user_id] = user.id
    redirect_to posts_path, :notice => "Logged in!"
  else
    redirect_to log_in_path, :notice => "Invalid email or password"
  end
end

def log_out
  reset_session
  redirect_to log_in_path, :notice => "Logged out!"
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :logout_required, :only => [ :new ]
  before_filter :admin_required, :only => [ :edit, :update ]

  def new
    @user = User.new
  end

  def create
    @user = User.create(params[:user])
    if @user.save
      redirect_to posts_path, notice: t("controllers.users.create.success")
    else
      render :new, notice: ("#{@user.errors.full_messages.first}")
    end
  end

  def edit
    @user = User.find(params[:id])
    render :new
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
    if @user.errors.any?
      flash[:notice] = @user.errors.full_messages.first
    else
      redirect_to posts_path, :notice => "User Updated sucessfully"
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Doxnews</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:notice] %>
<%= flash[:notice] %>
<% end %>

<%= yield %>

<%= link_to 'Log Out', log_out_path, :method => :post %>

</body>
</html>

app/views/posts/_form.html.slim
= form_for @post do |f|

  - if @post.errors.any?
    ul
      - @post.errors.full_messages.each do |msg|
        li = msg

  p
    = f.label :title, I18n.t("views.posts.title")
    br
    = f.text_field :title
  p
    = f.label :url, I18n.t("views.posts.url")
    br
    = f.text_field :url
  p
    = f.label :body, I18n.t("views.posts.body")
    br
    = f.text_area :body, { cols: "90", rows: "10" }
  p
    = f.submit I18n.t("views.posts.submit")

app/views/posts/index.html.slim
h1 Published Posts

hr
  = link_to "New Post", new_post_path
hr
  h4 
    = 'My Posts: '
    = link_to 'Published', my_posts_path
    = ' / '
    = link_to 'Unpublished', my_posts_path(:state => 'unpublished')


- if @posts.present?
  ul
    - @posts.each do |post|
      li 
        = link_to "#{post.title} +#{post.up_votes_count} -#{post.down_votes_count}", post.url
        - if current_user.admin?
          = link_to '(delete)', post_path(post), :method => :delete, :data => {:confirm => 'Are you sure you want to delete this post?'}
      - if post.body.present?
        = post.body
      = link_to 'Up', up_vote_post_path(post), :method => :post
      - if current_user.admin?
        = '/'
        = link_to 'Down', down_vote_post_path(post), :method => :post
- else
  p There are no posts.

= will_paginate @posts

app/views/posts/new.html.slim
h1 New Post

= render "form"

app/views/users/_form.html.slim
= form_for @user do |f|

  - if @user.errors.any?
    ul
      - @user.errors.full_messages.each do |msg|
        li = msg

  p
    = f.label :name, I18n.t("views.users.name")
    br
    = f.text_field :name
  p
    = f.label :email, I18n.t("views.users.email")
    br
    = f.text_field :email
  p
    = f.label :password, I18n.t("views.users.password")
    br
    = f.password_field :password
  p
    = f.label :password_confirmation, I18n.t("views.users.password_confirmation")
    br
    = f.password_field :password_confirmation
  p
    = f.submit I18n.t("views.posts.submit")

app/views/users/log_in.html.slim
= form_tag sessions_path do

  p
    = label_tag :email, I18n.t("views.users.email")
    br
    = text_field_tag :email
  p
    = label_tag :password, I18n.t("views.users.password")
    br
    = password_field_tag :password
  p
    = submit_tag I18n.t("views.posts.submit")

app/views/users/new.html.slim
h1 New User

= render "form"

app/views/welcome/index.html.slim
h2 Welcome
p
  ' Fork this repository, create a new branch and pull-request with your changes. Here's a guide if you're new to
  '
  = link_to "Github", "https://help.github.com/articles/using-pull-requests"
  '. Once completed send us a link to your pull-request.


h3 Tasks you should complete:

p 1. Add authentication and basic access level control to the application.
ul
  li There should be a user and an admin account
  li User is able to create posts
  li In addition Admin is *also* able to delete posts and edit user's profiles

p 2. Posts created should belong to the currently logged in user
ul
 li As a logged in user I'd like to see a list of all my posts (published and unpublished)

p 3. Add voting functionality
ul
  li User is able to up-vote *other* people's posts but not down-vote
  li Admin is able to up-vote and down-vote

p 4. Identify and implement performance enhancements
ul
  li The Posts index view is abit inefficient. There are things you can do app and DB level to make it more efficient. Please address these issues.
  li A couple things to consider: caching, migrations, query optimizatons...

h3 Things to keep in mind:
p The purpose of this app is to gauge your ability to:
ul
  li Problem solve and think critically
  li Follow directions while making educated decisions on your own
  li Implement a solution using Ruby on Rails that you're proud of
  li Program efficiently, ideally you'd spend less than 3 hours on the assignment

h3 Bonus
ul
  li Write specs for a model/controller that you feel should have them
  li Show us your JS skills in a creative an benefitial feature
  li Feel free to add/use anything else you think would highlight your recent skills
  li Make any improvements to the code you feel necessary

br
p = link_to "Go to the app", posts_path